## Importing Modules

In [173]:
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt 
import seaborn as sns

## Loading the Dataset

In [174]:
df_hour = pd.read_csv('data/raw/hour.csv')

df_hour_clean = df_hour.copy()
df_hour_clean.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

## Data Cleaning

In [175]:
df_hour_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

### Convert dteday to DateTime

In [176]:
df_hour_clean["dteday"] = pd.to_datetime(df_hour_clean["dteday"])

df_hour_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  datetime64[ns]
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(12)
memory usage: 2.3 MB

### Create Datetime column 
datetime = dteday + hr

In [177]:
df_hour_clean['datetime'] = (
    df_hour_clean['dteday'] +
    pd.to_timedelta(df_hour_clean['hr'] , unit='hr')
)

df_hour_clean.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,datetime
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16,2011-01-01 00:00:00
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40,2011-01-01 01:00:00
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32,2011-01-01 02:00:00
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13,2011-01-01 03:00:00
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1,2011-01-01 04:00:00

In [178]:
# Drop dteday

df_hour_clean = df_hour_clean.drop(columns=['dteday'] , axis=1)
df_hour_clean.head()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,datetime
0,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16,2011-01-01 00:00:00
1,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40,2011-01-01 01:00:00
2,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32,2011-01-01 02:00:00
3,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13,2011-01-01 03:00:00
4,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1,2011-01-01 04:00:00

### Sort Chronologically
Time series models require data in time order

In [179]:
df_hour_clean = df_hour_clean.sort_values('datetime')
df_hour_clean.head(7)

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,datetime
0,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16,2011-01-01 00:00:00
1,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40,2011-01-01 01:00:00
2,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32,2011-01-01 02:00:00
3,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13,2011-01-01 03:00:00
4,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1,2011-01-01 04:00:00
5,6,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,0,1,1,2011-01-01 05:00:00
6,7,1,0,1,6,0,6,0,1,0.22,0.2727,0.80,0.0000,2,0,2,2011-01-01 06:00:00

In [180]:
df_hour_clean = df_hour_clean.reset_index(drop=True)
df_hour_clean.head(7)

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,datetime
0,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16,2011-01-01 00:00:00
1,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40,2011-01-01 01:00:00
2,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32,2011-01-01 02:00:00
3,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13,2011-01-01 03:00:00
4,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1,2011-01-01 04:00:00
5,6,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,0,1,1,2011-01-01 05:00:00
6,7,1,0,1,6,0,6,0,1,0.22,0.2727,0.80,0.0000,2,0,2,2011-01-01 06:00:00

### Creating datetime as index

In [181]:
df_hour_clean.set_index('datetime' , inplace=True)
df_hour_clean.head()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
datetime,,,,,,,,,,,,,,,,
2011-01-01 00:00:00,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
2011-01-01 01:00:00,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2011-01-01 02:00:00,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
2011-01-01 03:00:00,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
2011-01-01 04:00:00,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

### Removing unnessasary columns

In [182]:
df_hour_clean.drop(columns=['instant'] , axis=1 , inplace=True)
df_hour_clean.head()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
datetime,,,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
2011-01-01 01:00:00,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2011-01-01 02:00:00,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
2011-01-01 03:00:00,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
2011-01-01 04:00:00,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

### Removing leakage columns

The dataset defines:

cnt = casual + registered

If the model receives both casual and registered, it can simply compute:
100 + 250 = 350

It doesn't need to learn anything.

In [183]:
df_hour_clean.drop(columns=['casual' , 'registered'] , axis=1 , inplace=True)
df_hour_clean.head()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
datetime,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
2011-01-01 01:00:00,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2011-01-01 02:00:00,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
2011-01-01 03:00:00,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
2011-01-01 04:00:00,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

### Saving the Data

In [184]:
df_hour_clean.to_csv('data/processed/hour_clean.csv')

# Feature Engineering

In [185]:
df = df_hour_clean.copy()
df.head()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
datetime,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
2011-01-01 01:00:00,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2011-01-01 02:00:00,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
2011-01-01 03:00:00,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
2011-01-01 04:00:00,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

### Cyclic Encoding

Time is cyclic, not linear.<br>
Linear numbers make 23 and 0 look far apart, even though they're consecutive.<br>
So we form a cycle using sine and cosine values

In [186]:
# Hour 
df["hr_sin"] = np.sin(2 * np.pi * df["hr"] / 24)
df["hr_cos"] = np.cos(2 * np.pi * df["hr"] / 24)

# Week
df["week_sin"] = np.sin(2 * np.pi * df["weekday"] / 7)
df["week_cos"] = np.cos(2 * np.pi * df["weekday"] / 7)

# Month
df["mnth_sin"] = np.sin(2 * np.pi * df["mnth"] / 12)
df["mnth_cos"] = np.cos(2 * np.pi * df["mnth"] / 12)

df.head()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt,hr_sin,hr_cos,week_sin,week_cos,mnth_sin,mnth_cos
datetime,,,,,,,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16,0.000000,1.000000,-0.781831,0.62349,0.5,0.866025
2011-01-01 01:00:00,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40,0.258819,0.965926,-0.781831,0.62349,0.5,0.866025
2011-01-01 02:00:00,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32,0.500000,0.866025,-0.781831,0.62349,0.5,0.866025
2011-01-01 03:00:00,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13,0.707107,0.707107,-0.781831,0.62349,0.5,0.866025
2011-01-01 04:00:00,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1,0.866025,0.500000,-0.781831,0.62349,0.5,0.866025

### Creating Lag Features

Creating<br>
lag_1 : previous hour demand <br>
lag_24 : previous day demand in same hour <br>
lag_168 : previous week demand in same hour

In [187]:
df['lag_1'] = df['cnt'].shift(1)
df['lag_24'] = df['cnt'].shift(24)
df['lag_168'] = df['cnt'].shift(168)

df.head()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,...,cnt,hr_sin,hr_cos,week_sin,week_cos,mnth_sin,mnth_cos,lag_1,lag_24,lag_168
datetime,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,1,0,0,6,0,1,0.24,0.2879,...,16,0.000000,1.000000,-0.781831,0.62349,0.5,0.866025,NaN,NaN,NaN
2011-01-01 01:00:00,1,0,1,1,0,6,0,1,0.22,0.2727,...,40,0.258819,0.965926,-0.781831,0.62349,0.5,0.866025,16.0,NaN,NaN
2011-01-01 02:00:00,1,0,1,2,0,6,0,1,0.22,0.2727,...,32,0.500000,0.866025,-0.781831,0.62349,0.5,0.866025,40.0,NaN,NaN
2011-01-01 03:00:00,1,0,1,3,0,6,0,1,0.24,0.2879,...,13,0.707107,0.707107,-0.781831,0.62349,0.5,0.866025,32.0,NaN,NaN
2011-01-01 04:00:00,1,0,1,4,0,6,0,1,0.24,0.2879,...,1,0.866025,0.500000,-0.781831,0.62349,0.5,0.866025,13.0,NaN,NaN

### Rolling Window Features

Instead of looking at one previous value,
look at the average of several previous values
<br>
rolling mean , median , standard deviation

In [188]:
df['rolling_mean'] = df['cnt'].rolling(window=24).mean()
df['rolling_median'] = df['cnt'].rolling(window=24).median()
df['rolling_std'] = df['cnt'].rolling(window=24).std()

df.tail()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,...,week_sin,week_cos,mnth_sin,mnth_cos,lag_1,lag_24,lag_168,rolling_mean,rolling_median,rolling_std
datetime,,,,,,,,,,,,,,,,,,,,,
2012-12-31 19:00:00,1,1,12,19,0,1,1,2,0.26,0.2576,...,0.781831,0.62349,-2.449294e-16,1.0,122.0,102.0,26.0,110.166667,102.0,89.887208
2012-12-31 20:00:00,1,1,12,20,0,1,1,2,0.26,0.2576,...,0.781831,0.62349,-2.449294e-16,1.0,119.0,72.0,18.0,110.875000,104.0,89.640011
2012-12-31 21:00:00,1,1,12,21,0,1,1,1,0.26,0.2576,...,0.781831,0.62349,-2.449294e-16,1.0,89.0,47.0,23.0,112.666667,104.5,88.732949
2012-12-31 22:00:00,1,1,12,22,0,1,1,1,0.26,0.2727,...,0.781831,0.62349,-2.449294e-16,1.0,90.0,36.0,22.0,113.708333,104.5,87.936973
2012-12-31 23:00:00,1,1,12,23,0,1,1,1,0.26,0.2727,...,0.781831,0.62349,-2.449294e-16,1.0,61.0,49.0,12.0,113.708333,104.5,87.936973

### Adding peak hours column

In [189]:
df["is_peak_hour"] = (
    df["hr"].isin([7,8,9,17,18,19])
).astype(int)

df.sample(5)

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,...,week_cos,mnth_sin,mnth_cos,lag_1,lag_24,lag_168,rolling_mean,rolling_median,rolling_std,is_peak_hour
datetime,,,,,,,,,,,,,,,,,,,,,
2012-05-31 15:00:00,2,1,5,15,0,4,1,1,0.76,0.6667,...,-0.900969,0.500000,-8.660254e-01,254.0,275.0,291.0,296.125000,272.0,241.242132,0
2011-10-09 05:00:00,4,0,10,5,0,0,0,1,0.44,0.4394,...,1.000000,-0.866025,5.000000e-01,14.0,8.0,7.0,228.875000,194.5,170.332747,0
2012-08-22 06:00:00,3,1,8,6,0,3,1,1,0.62,0.5909,...,-0.900969,-0.866025,-5.000000e-01,40.0,169.0,172.0,292.958333,291.0,232.901636,0
2011-11-23 03:00:00,4,0,11,3,0,3,1,3,0.50,0.4848,...,-0.900969,-0.500000,8.660254e-01,6.0,3.0,5.0,67.125000,45.5,57.285185,0
2012-03-21 19:00:00,2,1,3,19,0,3,1,1,0.60,0.6061,...,-0.900969,1.000000,6.123234e-17,779.0,555.0,472.0,258.958333,227.0,221.005111,1

### Adding Interaction Features

weather x hr

temp x hr 

temp x humidity

In [190]:
df['weather_hr'] = df['weathersit'] * df['hr']
df['temp_hr'] = df['temp'] * df['hr']
df['temp_hum'] = df['temp'] * df['hum']

df.head()

,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,...,lag_1,lag_24,lag_168,rolling_mean,rolling_median,rolling_std,is_peak_hour,weather_hr,temp_hr,temp_hum
datetime,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,1,0,0,6,0,1,0.24,0.2879,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.00,0.1944
2011-01-01 01:00:00,1,0,1,1,0,6,0,1,0.22,0.2727,...,16.0,NaN,NaN,NaN,NaN,NaN,0,1,0.22,0.1760
2011-01-01 02:00:00,1,0,1,2,0,6,0,1,0.22,0.2727,...,40.0,NaN,NaN,NaN,NaN,NaN,0,2,0.44,0.1760
2011-01-01 03:00:00,1,0,1,3,0,6,0,1,0.24,0.2879,...,32.0,NaN,NaN,NaN,NaN,NaN,0,3,0.72,0.1800
2011-01-01 04:00:00,1,0,1,4,0,6,0,1,0.24,0.2879,...,13.0,NaN,NaN,NaN,NaN,NaN,0,4,0.96,0.1800

### Handling Missing values

In [191]:
df.isna().sum()

season              0
yr                  0
mnth                0
hr                  0
holiday             0
weekday             0
workingday          0
weathersit          0
temp                0
atemp               0
hum                 0
windspeed           0
cnt                 0
hr_sin              0
hr_cos              0
week_sin            0
week_cos            0
mnth_sin            0
mnth_cos            0
lag_1               1
lag_24             24
lag_168           168
rolling_mean       23
rolling_median     23
rolling_std        23
is_peak_hour        0
weather_hr          0
temp_hr             0
temp_hum            0
dtype: int64

In [192]:
df.dropna(inplace=True)
df.isna().sum()

season            0
yr                0
mnth              0
hr                0
holiday           0
weekday           0
workingday        0
weathersit        0
temp              0
atemp             0
hum               0
windspeed         0
cnt               0
hr_sin            0
hr_cos            0
week_sin          0
week_cos          0
mnth_sin          0
mnth_cos          0
lag_1             0
lag_24            0
lag_168           0
rolling_mean      0
rolling_median    0
rolling_std       0
is_peak_hour      0
weather_hr        0
temp_hr           0
temp_hum          0
dtype: int64

#### Saving df

In [193]:
df.to_csv('data/processed/hour_features.csv')